-- AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/analysis.ipynb (unless otherwise specified).
with stories as (
  select
    * except (`by`),
    `by` as submitter_id,
  from {{ source('public_datasets', 'full_stories') }}
),
latest_stories as (
  select 
     id as post_id, 
     title,
     url,
     submitter_id,
     text as content,
     timestamp as submit_timestamp, -- no need for time since timestamp == time
     ifnull(dead,false) as dead,  
     score as post_score,
     cast(parent as int64) as parent_id,
     type as post_type,
     ranking,
     deleted,
     descendants
   from stories
   order by submit_timestamp desc
)
select *
from latest_stories
