-- AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/analysis.ipynb (unless otherwise specified).
with stories as (
  select
    * except (`by`),
    `by` as submitter_id,
  from {{ source('public_datasets', 'full_stories') }}
),
latest_stories as (
  select 
     id as post_id, 
     title,
     url,
     submitter_id,
     text as content,
     timestamp as submit_timestamp,
     dead as post_status,  
     score as post_score,
     cast(parent as numeric) as parent_id,
     type as post_type,
   from stories
   order by submit_timestamp desc
)
select *
from latest_stories
