-- AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/latest_job_posts_build.ipynb (unless otherwise specified).
{{ config(materialized='table') }}
-- select from last 6 months (assuming monthly cadence)
with latest_hiring as
( select post_id,
  from {{ ref('latest_whos_hiring_articles') }}
),
latest_job_posts as 
(
  select p.*
  from {{ ref('hn_posts') }} p
  inner join latest_hiring h
  on p.parent_id = h.post_id
)
select *  
from latest_job_posts
