-- AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/analysis.ipynb (unless otherwise specified).
select count(*) as top_level_comment_count
from {{ ref('hn_posts') }}
where post_type = 'comment' 
  and parent_id is null
