-- AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/analysis.ipynb (unless otherwise specified).
select parent_id, count(*) as child_count
from {{ ref('hn_posts') }}
where parent_id in (32201573,32201535,32201615, 32201513)
group by parent_id
