-- AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/analysis.ipynb (unless otherwise specified).
select descendants, count(*) as instances
from {{ ref('hn_posts') }}
where descendants is not null
group by descendants
order by instances desc
