-- AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/analysis.ipynb (unless otherwise specified).
with child as (
    select post_id as child_id,
           parent_id,
    from {{ ref('hn_posts') }}
    where parent_id is not null
),
parent as (
    select post_id as parent_id,
    from  {{ ref('hn_posts') }}
),
parent_child as (
    select c.child_id,
           p.parent_id,
    from child c
    left join parent p
    on c.parent_id = p.parent_id
)
select count(*) as unmatched_count
from parent_child 
where parent_id is null
