-- AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/analysis.ipynb (unless otherwise specified).
select type as type, count(*) as type_count
from {{ source('public_datasets', 'full_stories') }}
group by type 
order by type_count desc
