-- AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/whos_hiring.ipynb (unless otherwise specified).
select *
from {{ ref('hn_posts') }}
where post_type = 'story'
 and  lower(title) like '%ask hn: who is hiring%'
 and  submitter_id = 'whoishiring'
order by submit_timestamp desc
